SIMULATION:
  COARSE_SPACING: 0.05
  FINE_SIZE: 100
  COARSE_SIZE: 20

NETWORK:
  NUM_HIDDEN_LAYERS: 4
  NUM_NEURONS: 10

TRAINING:
  N_EPOCHS: 200
  LEARNING_RATE: 0.001
  MIN_LEARNING_RATE: 0.0001
  EVALUATE: True
  INVARIANCE: True
  TENSOR_INVARIANTS: True
  TRAINING_FRACTION: 0.8
  BATCH_SIZE: 1
  
