SIMULATION:
  COARSE_SPACING: 0.05
  FINE_SIZE: 100
  COARSE_SIZE: 20

TRAINING:
  N_EPOCHS: 2500
  LEARNING_RATE: 0.001
  EVALUATE: True
  INVARIANCE: True
  TENSOR_INVARIANTS: True
  TRAINING_FRACTION: 0.8
  BATCH_SIZE: 1
  
